In [6]:
from plotly_calplot import calplot
import pandas as pd
import nbformat
import plotly.express as px
import matplotlib.pyplot as plt
import plotly.express as px
import numpy as np

In [7]:
# ディレクトリをここに設定
%cd /Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/access_data

/Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/access_data

# 地図を描こう
### アクセスされているけど，まだ緯度経度を登録していない地域を検出

In [8]:
df = pd.read_csv("/Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/access_data/ユーザー属性の詳細_地域.csv", encoding="shift-jis")
df = df[df["蝨ｰ蝓"] != "(not set)"]
df = df[df["蟶ょ玄逕ｺ譚"] != "(not set)"]

# 都市名と県名の情報を作成
df["都市名"] = df["蝨ｰ蝓"] + "," + df["蟶ょ玄逕ｺ譚"]
df

,蝨ｰ蝓,蟶ょ玄逕ｺ譚,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ,譁ｰ隕上Θ繝ｼ繧ｶ繝ｼ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ縺ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝育紫,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝医ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰｼ1 繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧奇ｼ,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧翫ｮ蟷ｳ蝮お繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝域凾髢,繧､繝吶Φ繝域焚,繧ｭ繝ｼ繧､繝吶Φ繝,繝ｦ繝ｼ繧ｶ繝ｼ 繧ｭ繝ｼ繧､繝吶Φ繝育紫,蜷郁ｨ亥庶逶,都市名
2,Tokyo,Shinjuku City,146,135,54,0.341772,0.369863,14.095890,570,0,0,0,"Tokyo,Shinjuku City"
3,Miyagi,Sendai,133,130,356,0.732510,2.676692,141.105263,4245,0,0,0,"Miyagi,Sendai"
4,Osaka,Osaka,79,73,33,0.383721,0.417722,10.848101,333,0,0,0,"Osaka,Osaka"
5,Tokyo,Shibuya,63,60,28,0.388889,0.444444,18.761905,302,0,0,0,"Tokyo,Shibuya"
6,Tokyo,Minato City,44,38,20,0.416667,0.454545,22.909091,234,0,0,0,"Tokyo,Minato City"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
273,Yamagata,Tsuruoka,1,1,0,0.000000,0.000000,0.000000,3,0,0,0,"Yamagata,Tsuruoka"
274,Zurich,Zurich,1,1,0,0.000000,0.000000,0.000000,3,0,0,0,"Zurich,Zurich"
275,Guangdong Province,Guangzhou,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Guangdong Province,Guangzhou"
276,Hokkaido,Asahikawa,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Hokkaido,Asahikawa"
277,Ontario,Toronto,0,0,0,0.000000,0.000000,0.000000,2,0,0,0,"Ontario,Toronto"

In [9]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
geolocator = Nominatim(user_agent="myapp", timeout=10)

for index, row in df.iterrows():
    geolocator = Nominatim(user_agent="myGeocoder")
    geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1)
    location = geocode(row["都市名"])
    if location:
        df.at[index, "緯度"] = location.latitude
        df.at[index, "経度"] = location.longitude
    else:
        df.at[index, "緯度"] = None
        df.at[index, "経度"] = None
    # 進捗表示
    print(f"Processing {index + 1}/{len(df)}: {row['都市名']}")

df

Processing 3/264: Tokyo,Shinjuku City
Processing 4/264: Miyagi,Sendai
Processing 5/264: Osaka,Osaka
Processing 6/264: Tokyo,Shibuya
Processing 7/264: Tokyo,Minato City
Processing 8/264: Hokkaido,Sapporo
Processing 9/264: Kanagawa,Yokohama
Processing 10/264: Aichi,Nagoya
Processing 11/264: Tokyo,Ota City
Processing 12/264: Kyoto,Kyoto
Processing 13/264: Tokyo,Setagaya City
Processing 14/264: Hyogo,Kobe
Processing 15/264: Fukuoka,Fukuoka
Processing 16/264: Tokyo,Arakawa City
Processing 17/264: Tokyo,Chuo City
Processing 18/264: Tokyo,Chiyoda City
Processing 19/264: Tokyo,Bunkyo City
Processing 20/264: Chiba,Chiba

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Hyogo,Nishinomiya',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Hyogo,Nishinomiya',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Hyogo,Nishinomiya',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Hyogo%2CNishinomiya&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

Processing 21/264: Hyogo,Nishinomiya

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Tokyo,Suginami City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Tokyo,Suginami City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Tokyo,Suginami City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CSuginami+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

Processing 22/264: Tokyo,Suginami City

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Ibaraki,Tsukuba',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Ibaraki,Tsukuba',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Ibaraki,Tsukuba',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Ibaraki%2CTsukuba&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

Processing 23/264: Ibaraki,Tsukuba

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Tokyo,Itabashi City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Tokyo,Itabashi City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Tokyo,Itabashi City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CItabashi+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

Processing 24/264: Tokyo,Itabashi City

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Tokyo,Koto City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Tokyo,Koto City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Tokyo,Koto City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CKoto+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

Processing 25/264: Tokyo,Koto City

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Tokyo,Nerima City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Tokyo,Nerima City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Tokyo,Nerima City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CNerima+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

Processing 26/264: Tokyo,Nerima City

RateLimiter caught an error, retrying (0/2 tries). Called with (*('Tokyo,Shinagawa City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter caught an error, retrying (1/2 tries). Called with (*('Tokyo,Shinagawa City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 136, in _retries_gen
    yield i  # Run the function.
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))
RateLimiter swallowed an error after 2 retries. Called with (*('Tokyo,Shinagawa City',), **{}).
Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 537, in _make_request
    response = conn.getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connection.py", line 466, in getresponse
    httplib_response = super().getresponse()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1307, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/ssl.py", line 1163, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 539, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 877, in urlopen
    return self.urlopen(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 482, in _request
    resp = self.session.get(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/extra/rate_limiter.py", line 274, in __call__
    res = self.func(*args, **kwargs)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/nominatim.py", line 297, in geocode
    return self._call_geocoder(url, callback, timeout=timeout)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/geocoders/base.py", line 368, in _call_geocoder
    result = self.adapter.get_json(url, timeout=timeout, headers=req_headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 472, in get_json
    resp = self._request(url, timeout=timeout, headers=headers)
  File "/Users/yamaguchiyuhei/.julia/conda/3/aarch64/lib/python3.10/site-packages/geopy/adapters.py", line 494, in _request
    raise GeocoderUnavailable(message)
geopy.exc.GeocoderUnavailable: HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Max retries exceeded with url: /search?q=Tokyo%2CShinagawa+City&format=json&limit=1 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)"))

Processing 27/264: Tokyo,Shinagawa City

KeyboardInterrupt:

In [11]:
df.head(25)

,蝨ｰ蝓,蟶ょ玄逕ｺ譚,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ,譁ｰ隕上Θ繝ｼ繧ｶ繝ｼ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ縺ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰ,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝育紫,繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝医ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰｼ1 繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧奇ｼ,繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧翫ｮ蟷ｳ蝮お繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝域凾髢,繧､繝吶Φ繝域焚,繧ｭ繝ｼ繧､繝吶Φ繝,繝ｦ繝ｼ繧ｶ繝ｼ 繧ｭ繝ｼ繧､繝吶Φ繝育紫,蜷郁ｨ亥庶逶,都市名,緯度,経度
2,Tokyo,Shinjuku City,146,135,54,0.341772,0.369863,14.095890,570,0,0,0,"Tokyo,Shinjuku City",35.693860,139.703447
3,Miyagi,Sendai,133,130,356,0.732510,2.676692,141.105263,4245,0,0,0,"Miyagi,Sendai",38.267755,140.869150
4,Osaka,Osaka,79,73,33,0.383721,0.417722,10.848101,333,0,0,0,"Osaka,Osaka",34.693757,135.501454
5,Tokyo,Shibuya,63,60,28,0.388889,0.444444,18.761905,302,0,0,0,"Tokyo,Shibuya",35.663371,139.696495
6,Tokyo,Minato City,44,38,20,0.416667,0.454545,22.909091,234,0,0,0,"Tokyo,Minato City",35.654842,139.760987
7,Hokkaido,Sapporo,43,38,23,0.460000,0.534884,24.418605,258,0,0,0,"Hokkaido,Sapporo",43.061936,141.354292
8,Kanagawa,Yokohama,40,33,25,0.510204,0.625000,47.800000,246,0,0,0,"Kanagawa,Yokohama",35.450338,139.634380
9,Aichi,Nagoya,37,33,27,0.519231,0.729730,28.108108,254,0,0,0,"Aichi,Nagoya",35.185105,136.899844
10,Tokyo,Ota City,32,27,22,0.564103,0.687500,28.250000,154,0,0,0,"Tokyo,Ota City",35.561389,139.716081
11,Kyoto,Kyoto,31,30,13,0.371429,0.419355,18.903226,149,0,0,0,"Kyoto,Kyoto",34.985350,135.758766
12,Tokyo,Setagaya City,28,25,18,0.500000,0.642857,37.035714,164,0,0,0,"Tokyo,Setagaya City",35.646530,139.653250
13,Hyogo,Kobe,23,22,10,0.400000,0.434783,12.869565,84,0,0,0,"Hyogo,Kobe",34.693238,135.194376
14,Fukuoka,Fukuoka,21,19,12,0.521739,0.571429,25.238095,121,0,0,0,"Fukuoka,Fukuoka",33.589899,130.401751
15,Tokyo,Arakawa City,21,19,6,0.285714,0.285714,8.857143,75,0,0,0,"Tokyo,Arakawa City",35.737036,139.783405
16,Tokyo,Chuo City,21,18,11,0.458333,0.523810,14.904762,93,0,0,0,"Tokyo,Chuo City",34.689962,135.506431
17,Tokyo,Chiyoda City,20,17,10,0.384615,0.500000,42.900000,181,0,0,0,"Tokyo,Chiyoda City",35.694163,139.753562
18,Tokyo,Bunkyo City,18,15,12,0.500000,0.666667,51.666667,154,0,0,0,"Tokyo,Bunkyo City",35.706330,139.753381
19,Chiba,Chiba,14,11,13,0.590909,0.928571,46.642857,100,0,0,0,"Chiba,Chiba",35.607063,140.106265
20,Hyogo,Nishinomiya,14,9,11,0.550000,0.785714,30.642857,93,0,0,0,"Hyogo,Nishinomiya",NaN,NaN
21,Tokyo,Suginami City,14,11,12,0.750000,0.857143,20.785714,87,0,0,0,"Tokyo,Suginami City",NaN,NaN
22,Ibaraki,Tsukuba,12,11,9,0.642857,0.750000,25.583333,91,0,0,0,"Ibaraki,Tsukuba",NaN,NaN
23,Tokyo,Itabashi City,12,9,8,0.666667,0.666667,25.750000,55,0,0,0,"Tokyo,Itabashi City",NaN,NaN
24,Tokyo,Koto City,12,11,7,0.500000,0.583333,32.666667,63,0,0,0,"Tokyo,Koto City",NaN,NaN
25,Tokyo,Nerima City,12,8,8,0.571429,0.666667,26.750000,55,0,0,0,"Tokyo,Nerima City",NaN,NaN
26,Tokyo,Shinagawa City,11,11,4,0.333333,0.363636,15.545455,46,0,0,0,"Tokyo,Shinagawa City",NaN,NaN

In [5]:
df["freq"] = df['繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ']

fig = px.scatter_mapbox(
    df,
    lat='緯度',  # 緯度
    lon='経度',  # 経度
    size='freq',
    zoom=4,
    size_max=20,
    color_discrete_sequence=["#00d5ff"]
)

fig.update_layout(
    title_font_size=20,
    geo=dict(
        showcountries=True,  # 国境を表示
        showcoastlines=True,  # 海岸線を表示
        coastlinecolor="Gray",
        landcolor="LightYellow"
    ),
    mapbox_style='carto-darkmatter',
    margin=dict(l=0, r=0, t=0, b=0),
    legend=dict(
        x=1,  # 凡例を右に移動
        y=1,  # 凡例を上に移動
        xanchor="right",  # 凡例の右端を基準に配置
        yanchor="top",  # 凡例の上端を基準に配置
        bgcolor="rgba(255, 255, 255, 0.7)",  # 背景を半透明の白に設定
        bordercolor="Black",  # 枠線の色
        borderwidth=1  # 枠線の幅
    ),
    # mapの初期表示の中心を日本に
    mapbox=dict(
        center=dict(lat=38.5548, lon=137.1529),  # 日本の緯度と経度
    )
)

fig.show()

ValueError: Value of 'lat' is not the name of a column in 'data_frame'. Expected one of ['蝨ｰ蝓', '蟶ょ玄逕ｺ譚', '繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ', '譁ｰ隕上Θ繝ｼ繧ｶ繝ｼ謨ｰ', '繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ縺ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰ', '繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝育紫', '繧ｨ繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝医ｮ縺ゅ▲縺溘そ繝す繝ｧ繝ｳ謨ｰｼ1 繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧奇ｼ', '繧｢繧ｯ繝ぅ繝 繝ｦ繝ｼ繧ｶ繝ｼ縺ゅ◆繧翫ｮ蟷ｳ蝮お繝ｳ繧ｲ繝ｼ繧ｸ繝｡繝ｳ繝域凾髢', '繧､繝吶Φ繝域焚', '繧ｭ繝ｼ繧､繝吶Φ繝', '繝ｦ繝ｼ繧ｶ繝ｼ 繧ｭ繝ｼ繧､繝吶Φ繝育紫', '蜷郁ｨ亥庶逶', '都市名', 'freq'] but received: 緯度

In [52]:
fig.write_html("/Users/yamaguchiyuhei/Desktop/Ymgc19.github.io/html_figures/access_map.html")